# application.properties (all profiles)
spring.application.name=backend
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=${SHOW_SQL:false}
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true
spring.flyway.validate-on-migrate=false
logging.level.org.flywaydb=${FLYWAY_DEBUG:false}
logging.level.com.zaxxer.hikari=${HIKARI_DEBUG:false}

spring.security.oauth2.client.registration.my-client.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.my-client.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.my-client.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.my-client.provider=my-provider

spring.security.oauth2.client.provider.my-provider.token-uri=https://oauth.battle.net/token

spring.jpa.properties.hibernate.format_sql=true
springdoc.cache.disabled=true